# Generated by Django 5.0.6 on 2024-06-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maps', models.URLField()),
            ],
            options={
                'verbose_name': 'Maps',
                'verbose_name_plural': 'Mapses',
            },
        ),
    ]
