# Generated by Django 5.0.6 on 2024-06-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_mapsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner/Y%/m%/%d', verbose_name='image'),
        ),
    ]
