# Generated by Django 5.0.6 on 2024-06-21 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandmodel',
            options={'verbose_name': 'Brend', 'verbose_name_plural': '3.Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': '2.Categories'},
        ),
        migrations.AlterModelOptions(
            name='colormodel',
            options={'verbose_name': 'Color', 'verbose_name_plural': '5.Colors'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Product', 'verbose_name_plural': '1.Products'},
        ),
        migrations.AlterModelOptions(
            name='sizemodel',
            options={'verbose_name': 'Size', 'verbose_name_plural': '4.Sizes'},
        ),
        migrations.AlterModelOptions(
            name='tagmodel',
            options={'verbose_name': 'Tag', 'verbose_name_plural': '6.Tags'},
        ),
        migrations.AlterModelTable(
            name='brandmodel',
            table='Brends',
        ),
    ]
