# Generated by Django 5.0.6 on 2024-06-25 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_brandmodel_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='wishlist',
            table=None,
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.productmodel', verbose_name='product')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.wishlist', verbose_name='wishlist')),
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'WishLists',
                'db_table': 'Wishlist',
                'unique_together': {('wishlist', 'product')},
            },
        ),
    ]
